#   gem install mysql2
#
#   Ensure the pg gem is defined in your Gemfile
#   gem 'mysql2'
#

default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5

development:
  <<: *default
  database: dawProcessDb
  username: root
  password: 1234

production:
  <<: *default
  database: dawProcessDb
  username: root
  password: daw-db-pass16

#default: &default
#  adapter: postgresql
#  encoding: unicode
#  pool: 20

#development:
#  <<: *default
#  database: dawProcessDb
#  username: postgres
#  password: 1234
#  timeout: 5000
#  owner: postgres
#  host: localhost

