# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69daa342335e5c6d5b1026c33da77ef224a6175e4cf47faea7c8309992d45b5f0fe552cc25e215cf196bd86ac767003db7e30216c9827ea87e91842226aa49d6

test:
  secret_key_base: c0149d486899346010ee5ae432b9cb599f18b4245f373b13d1d6a32f4b617bc3ee7702216b8b568b72bf2e1baa965a29322c085c20f47d8b044dfa2d2612c157

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
